### ISSUE TITLE
Add a page under advanced? for LaraStan

### ISSUE THREAD

**Issue by dcblogdev** [laravel-modules-com/docs#5]
Install Larastan:

```
composer require larastan/larastan:^2.0 --dev
```

Then, create a `phpstan.neon` file in the root of your application. It might look like this:

```
includes:
    - vendor/larastan/larastan/extension.neon

parameters:

    paths:
        - app/

    # Level 9 is the highest level
    level: 5

#    ignoreErrors:
#        - '#PHPDoc tag @var#'
#
#    excludePaths:
#        - ./*/*/FileToBeExcluded.php
#
#    checkMissingIterableValueType: false
```

Run Larastan:

```
./vendor/bin/phpstan analyse
```
This won't look inside modules, Larastan does not know they exist.

Edit `phpstan.neon` add Modules to the path and exclude paths:

```
includes:
    - vendor/larastan/larastan/extension.neon

parameters:

    excludePaths:
        - Modules/*/tests/*

    paths:
        - app/
        - Modules/

    # Level 9 is the highest level
    level: 8

    checkGenericClassInNonGenericObjectType: false
```

Maybe merge https://github.com/barryvdh/laravel-ide-helper in or add a separate page, as this will need a config publishing and update to work with modules.
